default_platform(:ios)

desc "Get Xcode project version, set it to podspec and commit changes"
lane :update_podspec_version do
	# Get current project version number
  	version_number = get_version_number(
    	xcodeproj: "AirKit.xcodeproj",
    	target: "AirKit"
  	)

  	# Upgrade podspec verstion number
	version_bump_podspec(
		path: "AirKit.podspec",
		version_number: version_number
	)

	# Commit podspec changes
	git_commit(
		path: "AirKit.podspec",
		message: "Updated `AirKit.podspec` version to `#{version_number}`",
		allow_nothing_to_commit: true
	)

	# Push the commit to origin
	push_to_git_remote()
end

desc "Get Xcode project version, add git tag and push changes to trunk"
lane :push_pod do
	# Get current project version number
  	version_number = get_version_number(
    	xcodeproj: "AirKit.xcodeproj",
    	target: "AirKit"
  	)

  	# Add git tag if not exist and push to remote
  	if git_tag_exists(tag: version_number, remote: true)
  		UI.error "Tag `#{version_number}` was already exist"
  	else
  		add_git_tag(tag: version_number)
  		push_git_tags(tag: version_number.shellescape)
  	end
end