default_platform(:ios)

desc "Fetch Xcode project version and set it to podspec"
lane :update_podspec_version do
  	version_number = get_version_number(
    	xcodeproj: "AirKit.xcodeproj",
    	target: "AirKit"
  	)

	version_bump_podspec(
		path: "AirKit.podspec",
		version_number: version_number
	)
end
